baseURL = 'https://monsi.org'
languageCode = 'en-us'
title = 'Monsi'

[module]
  [[module.imports]]
    path = "github.com/rhazdon/hugo-theme-hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Software Engineer"

  disableReadOtherPosts = false
  enableSharingButtons = false
  enableGlobalLanguageMenu = false
  enableThemeToggle = true

  description = "Monsi's homepage"
  keywords = "homepage, cv"

[[params.social]]
  name = "email"
  url  = "mailto:mail@monsi.org"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/simon-kreuzer/"

[[params.social]]
  name = "github"
  url  = "https://github.com/SiKreuz"

[[params.social]]
  name = "mastodon"
  url = "https://tum.social/@monsi"

[[params.social]]
  name = "lastfm"
  url = "https://www.last.fm/user/herrmonsi"

[[params.social]]
  name = "discord"
  url = "https://discordapp.com/users/503269097807806475"

[[params.social]]
  name = "steam"
  url = "https://steamcommunity.com/id/herrmonsi/"

[[params.social]]
  name = "gpg"
  url = "https://gist.github.com/SiKreuz/8fd8995687920d6a0bd3ce7793231519"
